import { ComplaintModel, EmergencyModel, DepartmentModel, NotificationModel, TourismPlace, GovernmentOffice } from '../types';

export const APP_COLORS = {
  primary: '#00695C',
  primaryLight: '#00897B',
  primaryDark: '#004D40',
  secondary: '#00ACC1',
  accent: '#2E7D32',
  background: '#F8FAFC',
  darkBackground: '#121212',
  textPrimary: '#1A1A1A',
  textSecondary: '#616161',
  textMuted: '#7D8887',
  border: '#E1E8E6',
  cardBg: '#FFFFFF',
  status: {
    submitted: '#42A5F5',
    verified: '#26A69A',
    assigned: '#FFB300',
    inProgress: '#FB8C00',
    resolved: '#43A047',
    closed: '#757575',
    rejected: '#E53935',
  },
  emergency: {
    police: '#1565C0',
    ambulance: '#D32F2F',
    fire: '#FF5722',
    disaster: '#6A1B9A',
    women: '#C2185B',
    electricity: '#F57C00',
    water: '#0288D1',
  }
};

export const ONBOARDING_SLIDES = [
  {
    image: '/assets/on_boarding/onboarding1.png',
    fallbackIcon: 'Building2',
    title: 'Welcome to\nNamma Kanyakumari',
    subtitle: 'Connecting you directly with your local district administration for a cleaner, smarter Kanyakumari.',
  },
  {
    image: '/assets/on_boarding/onboarding2.png',
    fallbackIcon: 'Camera',
    title: 'Smart Issue Reporting',
    subtitle: 'Capture civic problems like damaged roads, streetlights, or water leaks with AI auto-tagging for fast resolution.',
  },
  {
    image: '/assets/on_boarding/onboarding3.png',
    fallbackIcon: 'Clock',
    title: 'Track Every Step',
    subtitle: 'Receive real-time updates as your complaints move from field verification to assigned officer resolution.',
  },
  {
    image: '/assets/on_boarding/onboarding4.png',
    fallbackIcon: 'ShieldAlert',
    title: 'Safe & Secure',
    subtitle: 'One-tap direct access to District Police, Fire Rescue, 108 Ambulance, and Coastal Disaster Management.',
  },
];

export const COMPLAINT_CATEGORIES = [
  'General',
  'Roads & Potholes',
  'Streetlights & Electricity',
  'Water Supply & Drainage',
  'Sanitation & Garbage',
  'Public Health & Sanitation',
  'Revenue & Land',
  'Other',
];

export const KANYAKUMARI_TALUKS = [
  'Agastheeswaram (Nagercoil)',
  'Thovalai (Boothapandi)',
  'Kalkulam (Thuckalay)',
  'Vilavancode (Kuzhithurai)',
  'Killiyoor (Karungal)',
  'Thiruvattar',
];

export const INITIAL_COMPLAINTS: ComplaintModel[] = [
  {
    complaintId: 'KK-2025-0841',
    userId: 'usr_demo_1',
    userName: 'Karthik Raja',
    phoneNumber: '9842145678',
    category: 'Roads & Potholes',
    title: 'Major pothole near Vadasery Bus Stand entrance',
    description: 'Deep road cave-in and broken asphalt after recent monsoon rains, causing traffic blocks and two-wheeler skid hazards.',
    imageUrls: ['https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80'],
    latitude: 8.1873,
    longitude: 77.4278,
    address: 'Near Vadasery Central Bus Stand, Nagercoil, Kanyakumari District - 629001',
    status: 'inProgress',
    priority: 'high',
    departmentId: 'dept_highways',
    departmentName: 'State Highways & Municipal Roads',
    assignedOfficerId: 'off_902',
    assignedOfficerName: 'Er. S. Murugesan (Asst. Executive Engineer)',
    aiDetected: true,
    aiPrediction: 'Asphalt Road Depression & Pothole',
    aiConfidence: 0.94,
    createdAt: '2025-05-10T09:30:00Z',
    updatedAt: '2025-05-11T14:20:00Z',
    isPublic: true,
  },
  {
    complaintId: 'KK-2025-0824',
    userId: 'usr_demo_1',
    userName: 'Karthik Raja',
    phoneNumber: '9842145678',
    category: 'Streetlights & Electricity',
    title: 'Streetlights non-functional along Kanyakumari Beach Road',
    description: 'Five consecutive LED street lamp poles have failed between Sunset Point and Gandhi Memorial, leaving tourists in darkness.',
    imageUrls: ['https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=800&q=80'],
    latitude: 8.0792,
    longitude: 77.5501,
    address: 'Beach Promenade Road, Kanyakumari Town - 629702',
    status: 'resolved',
    priority: 'medium',
    departmentId: 'dept_tangedco',
    departmentName: 'TANGEDCO Electrical Division',
    assignedOfficerId: 'off_411',
    assignedOfficerName: 'R. Christopher (Junior Engineer)',
    aiDetected: true,
    aiPrediction: 'Defective Public Lighting Fixture',
    aiConfidence: 0.91,
    createdAt: '2025-05-02T18:45:00Z',
    updatedAt: '2025-05-04T11:15:00Z',
    resolvedAt: '2025-05-04T11:15:00Z',
    isPublic: true,
  },
  {
    complaintId: 'KK-2025-0899',
    userId: 'usr_demo_1',
    userName: 'Karthik Raja',
    phoneNumber: '9842145678',
    category: 'Water Supply & Drainage',
    title: 'Underground drinking water pipeline burst at Thuckalay Market',
    description: 'High pressure municipal water pipeline leaking clean potable water onto the road and flooding market alleyway.',
    imageUrls: ['https://images.unsplash.com/photo-1584467735871-8e85353a8413?auto=format&fit=crop&w=800&q=80'],
    latitude: 8.2483,
    longitude: 77.3298,
    address: 'Main Bazaar Road, Thuckalay Municipality, Kalkulam Taluk - 629175',
    status: 'verified',
    priority: 'high',
    departmentId: 'dept_twad',
    departmentName: 'TWAD Board & Water Distribution',
    assignedOfficerId: 'off_109',
    assignedOfficerName: 'M. Anandaraj (AE Water Works)',
    aiDetected: true,
    aiPrediction: 'High Volume Water Main Leakage',
    aiConfidence: 0.96,
    createdAt: '2025-05-13T07:15:00Z',
    updatedAt: '2025-05-13T10:00:00Z',
    isPublic: true,
  },
  {
    complaintId: 'KK-2025-0912',
    userId: 'usr_demo_1',
    userName: 'Karthik Raja',
    phoneNumber: '9842145678',
    category: 'Sanitation & Garbage',
    title: 'Accumulated vegetable waste bin overflow at Colachel Harbor',
    description: 'Secondary waste container overflowing near fishing landing center requiring immediate municipal compact truck clearance.',
    imageUrls: ['https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&w=800&q=80'],
    latitude: 8.1755,
    longitude: 77.2589,
    address: 'Near Colachel Fish Landing Harbor, Colachel Municipality - 629251',
    status: 'submitted',
    priority: 'medium',
    departmentId: 'dept_sanitation',
    departmentName: 'Colachel Municipal Health & Sanitation',
    aiDetected: true,
    aiPrediction: 'Municipal Solid Waste Accumulation',
    aiConfidence: 0.88,
    createdAt: '2025-05-14T08:00:00Z',
    isPublic: true,
  }
];

export const EMERGENCY_SERVICES: EmergencyModel[] = [
  {
    id: 'em_police',
    name: 'District Police Control Room',
    description: 'Immediate police intervention, patrolling and crime reporting across Kanyakumari district.',
    type: 'police',
    phoneNumber: '100',
    alternatePhone: '04652-220100',
    address: 'District Police Office, Court Road, Nagercoil',
    latitude: 8.1833,
    longitude: 77.4119,
    icon: 'Shield',
    is24Hours: true,
    isActive: true,
  },
  {
    id: 'em_ambulance',
    name: '108 Emergency Ambulance',
    description: 'Tamil Nadu Health Systems free emergency ambulance service with GPS-dispatched medical response.',
    type: 'ambulance',
    phoneNumber: '108',
    alternatePhone: '04652-233108',
    address: 'Government Medical College Hospital, Asaripallam, Nagercoil',
    latitude: 8.1911,
    longitude: 77.3986,
    icon: 'Ambulance',
    is24Hours: true,
    isActive: true,
  },
  {
    id: 'em_fire',
    name: 'Fire & Rescue Services',
    description: 'Disaster, fire suppression, building rescue, flood extraction and industrial hazard relief.',
    type: 'fire',
    phoneNumber: '101',
    alternatePhone: '04652-232101',
    address: 'District Fire Station, Cape Road, Nagercoil',
    latitude: 8.1798,
    longitude: 77.4321,
    icon: 'Flame',
    is24Hours: true,
    isActive: true,
  },
  {
    id: 'em_disaster',
    name: 'District Disaster Management (DDMA)',
    description: 'Cyclone warnings, heavy rainfall alerts, sea surge response and coastal emergency operations.',
    type: 'disaster',
    phoneNumber: '1077',
    alternatePhone: '04652-231077',
    address: 'District Collectorate Complex, Nagercoil',
    latitude: 8.1888,
    longitude: 77.4167,
    icon: 'AlertTriangle',
    is24Hours: true,
    isActive: true,
  },
  {
    id: 'em_coastguard',
    name: 'Indian Coast Guard & Coastal Police',
    description: 'Marine search and rescue, fisherman distress alerts, and coastal security surveillance.',
    type: 'coastGuard',
    phoneNumber: '1093',
    alternatePhone: '04652-246093',
    address: 'Coastal Security Police Station, Chinna Muttom & Colachel',
    latitude: 8.0967,
    longitude: 77.5621,
    icon: 'Anchor',
    is24Hours: true,
    isActive: true,
  },
  {
    id: 'em_women',
    name: 'Women & Child Helpline',
    description: 'Toll-free 24/7 protection, emergency assistance, and counseling for women and children.',
    type: 'women',
    phoneNumber: '1091',
    alternatePhone: '181',
    address: 'All Women Police Station, Nagercoil & Thuckalay',
    latitude: 8.1812,
    longitude: 77.4201,
    icon: 'HeartHandshake',
    is24Hours: true,
    isActive: true,
  },
  {
    id: 'em_electricity',
    name: 'TNEB Power Breakdown Support',
    description: 'Report live wire snaps, transformer sparks, and extended power outages.',
    type: 'electricity',
    phoneNumber: '1912',
    alternatePhone: '9498794987',
    address: 'TANGEDCO Distribution Circle, Parvathipuram, Nagercoil',
    latitude: 8.1967,
    longitude: 77.3854,
    icon: 'Zap',
    is24Hours: true,
    isActive: true,
  },
];

export const DEPARTMENTS: DepartmentModel[] = [
  {
    departmentId: 'dept_collectorate',
    name: 'District Revenue & Administration',
    description: 'Revenue administration, certificates, grievance redressal and civil supplies.',
    icon: 'Building',
    phoneNumber: '04652-231000',
    email: 'collr-kny@nic.in',
    officeAddress: 'District Collectorate, Nagercoil - 629001',
    isActive: true,
    totalOfficers: 42,
    complaintCategories: ['Revenue & Land', 'General', 'Other'],
  },
  {
    departmentId: 'dept_municipality',
    name: 'Municipal Corporation Nagercoil',
    description: 'Urban roads, sanitation, street lighting, tax collection and civic amenities.',
    icon: 'Building2',
    phoneNumber: '04652-232222',
    email: 'commr.nagercoil@tn.gov.in',
    officeAddress: 'Corporation Head Office, Balamore Road, Nagercoil',
    isActive: true,
    totalOfficers: 58,
    complaintCategories: ['Roads & Potholes', 'Streetlights & Electricity', 'Sanitation & Garbage'],
  },
  {
    departmentId: 'dept_twad',
    name: 'TWAD Board & Water Supply',
    description: 'Pechiparai & Chittar water scheme management, distribution, and pipelines.',
    icon: 'Droplets',
    phoneNumber: '04652-278144',
    email: 'ee_twad_ngl@yahoo.co.in',
    officeAddress: 'TWAD Maintenance Division, Vadasery, Nagercoil',
    isActive: true,
    totalOfficers: 26,
    complaintCategories: ['Water Supply & Drainage'],
  },
  {
    departmentId: 'dept_tangedco',
    name: 'TANGEDCO Electricity Board',
    description: 'Power distribution, line maintenance, smart meters, and transformer repairs.',
    icon: 'Zap',
    phoneNumber: '1912',
    email: 'sethedkny@tnebnet.org',
    officeAddress: 'Electricity Campus, Parvathipuram, Nagercoil',
    isActive: true,
    totalOfficers: 65,
    complaintCategories: ['Streetlights & Electricity'],
  },
];

export const TOURISM_PLACES: TourismPlace[] = [
  {
    id: 'tour_vivekananda',
    name: 'Vivekananda Rock Memorial',
    tamilName: 'விவேகானந்தர் பாறை நினைவு மண்டபம்',
    tagline: 'Iconic monument situated on two adjacent rocks off the southern tip of mainland India.',
    description: 'Built in 1970 in honor of Swami Vivekananda who attained enlightenment here in 1892. Features the Shripada Mandapam and Vivekananda Mandapam, surrounded by the confluence of the Arabian Sea, Bay of Bengal, and Indian Ocean.',
    location: 'Offshore, Kanyakumari',
    timing: '08:00 AM - 04:30 PM (Ferry operates daily)',
    entryFee: '₹20 (Memorial) + ₹50 (Ferry Ride)',
    imageUrl: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80',
    highlights: ['Ferry Ride over Ocean Triveni Sangam', 'Meditation Hall (Dhyana Mandapam)', 'Footprint imprint of Goddess Kanya'],
  },
  {
    id: 'tour_thiruvalluvar',
    name: 'Thiruvalluvar Statue',
    tamilName: 'திருவள்ளுவர் சிலை',
    tagline: 'Magnificent 133-foot stone sculpture symbolizing the 133 chapters of Thirukkural.',
    description: 'Standing 133 feet tall on a 38-foot pedestal representing Virtue, Wealth, and Love. Sculpted by renowned sthapathi Dr. V. Ganapati Sthapati, this towering landmark overlooks the southern ocean.',
    location: 'Offshore Rock, Kanyakumari',
    timing: '08:00 AM - 04:30 PM',
    entryFee: 'Included with Vivekananda Rock ferry',
    imageUrl: 'https://images.unsplash.com/photo-1621847468516-1ed5d0df56fe?auto=format&fit=crop&w=800&q=80',
    highlights: ['133-foot architectural marvel', 'Carved entirely of solid granite blocks', 'Panoramic 360-degree ocean horizon'],
  },
  {
    id: 'tour_padmanabhapuram',
    name: 'Padmanabhapuram Palace',
    tamilName: 'பத்மநாபபுரம் அரண்மனை',
    tagline: 'World-renowned wooden palace complex demonstrating traditional Travancore architecture.',
    description: 'Located at the foothills of Veli Hills near Thuckalay. Constructed in the 16th century with intricate rosewood carvings, Belgian mirrors, polished black granite floorings, and antique murals.',
    location: 'Thuckalay, Kalkulam Taluk',
    timing: '09:00 AM - 04:30 PM (Closed on Mondays)',
    entryFee: '₹40 (Adults), ₹10 (Children)',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    highlights: ['King Council Chamber with mica windows', 'Single-tree carved granite pillars', 'Antique Clock Tower running since 1832'],
  },
  {
    id: 'tour_mathur',
    name: 'Mathur Hanging Trough (Aqueduct)',
    tamilName: 'மாத்தூர் தொங்கும் பாலம்',
    tagline: 'One of Asia’s longest and tallest flume aqueducts spanning across the Pahrali River.',
    description: 'Built across the lush Pahrali river valley for irrigation in Vilavancode and Kalkulam taluks. Soars over 115 feet high on 28 massive stone piers with breathtaking scenic views of Western Ghats rubber plantations.',
    location: 'Mathur, near Thiruvattar',
    timing: '06:30 AM - 06:30 PM',
    entryFee: '₹10 per person',
    imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    highlights: ['1,240 feet long walkway above the canopy', 'Panoramic vistas of green palm & rubber forests', 'Children play park and riverside picnic spot'],
  },
  {
    id: 'tour_vattakottai',
    name: 'Vattakottai Fort (Circular Fort)',
    tamilName: 'வட்டக்கோட்டை',
    tagline: '18th-century coastal granite fort built by Captain De Lannoy of Travancore army.',
    description: 'Located 6 km north-east of Kanyakumari overlooking calm blue beaches and windmill ridges. Built with granite ramparts, parade grounds, and observation watchtowers looking over the sea.',
    location: 'Agastheeswaram Taluk, near Kanyakumari',
    timing: '08:00 AM - 05:30 PM',
    entryFee: 'Free entry',
    imageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
    highlights: ['Coastal ramparts with sea breeze', 'Lush green landscaped lawns', 'Views of Western Ghats meeting the sea'],
  }
];

export const NOTIFICATIONS: NotificationModel[] = [
  {
    notificationId: 'notif_01',
    userId: 'usr_demo_1',
    title: 'Complaint Update: KK-2025-0841',
    body: 'Assigned Officer Er. S. Murugesan has scheduled inspection and tarmac filling at Vadasery Bus Stand.',
    type: 'complaint',
    complaintId: 'KK-2025-0841',
    isRead: false,
    createdAt: '2025-05-11T14:20:00Z',
  },
  {
    notificationId: 'notif_02',
    userId: 'usr_demo_1',
    title: 'District Weather Alert: Heavy Sea Swell',
    body: 'Fishermen and beach visitors are advised to avoid deep sea swimming along Kanyakumari & Colachel coast due to high swell waves.',
    type: 'emergency',
    isRead: false,
    createdAt: '2025-05-13T06:00:00Z',
  },
  {
    notificationId: 'notif_03',
    userId: 'usr_demo_1',
    title: 'Complaint Resolved: KK-2025-0824',
    body: 'Streetlights repaired and restored at Beach Promenade Road, Kanyakumari.',
    type: 'complaint',
    complaintId: 'KK-2025-0824',
    isRead: true,
    createdAt: '2025-05-04T11:15:00Z',
  }
];

export const DEMO_USER = {
  uid: 'usr_demo_1',
  fullName: 'Karthik Raja',
  email: 'karthik.raja@gmail.com',
  phoneNumber: '9842145678',
  profileImage: '',
  role: 'citizen' as const,
  isVerified: true,
  isActive: true,
  district: 'Kanyakumari',
  taluk: 'Agastheeswaram',
  village: 'Nagercoil Town',
  pincode: '629001',
  createdAt: '2025-01-15T10:00:00Z',
};
