// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCnhqSzk8_oyvmZm_OcJRWqgvdGMBZ-bM',
    appId: '1:21701660625:web:8992d265126cbb2a995af0',
    messagingSenderId: '21701660625',
    projectId: 'namma-kanyakumari',
    authDomain: 'namma-kanyakumari.firebaseapp.com',
    storageBucket: 'namma-kanyakumari.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDG-FBI9v9BVNgagIkwZjO9Z-hnivH7DA',
    appId: '1:21701660625:android:e2f3479ba5968be0995af0',
    messagingSenderId: '21701660625',
    projectId: 'namma-kanyakumari',
    storageBucket: 'namma-kanyakumari.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf1iealdIr4FzrQPWzZDxF0VwSqQfOEsE',
    appId: '1:21701660625:ios:6410db6e75b4e454995af0',
    messagingSenderId: '21701660625',
    projectId: 'namma-kanyakumari',
    storageBucket: 'namma-kanyakumari.firebasestorage.app',
    iosBundleId: 'com.example.nammaKanyakumari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf1iealdIr4FzrQPWzZDxF0VwSqQfOEsE',
    appId: '1:21701660625:ios:6410db6e75b4e454995af0',
    messagingSenderId: '21701660625',
    projectId: 'namma-kanyakumari',
    storageBucket: 'namma-kanyakumari.firebasestorage.app',
    iosBundleId: 'com.example.nammaKanyakumari',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCnhqSzk8_oyvmZm_OcJRWqgvdGMBZ-bM',
    appId: '1:21701660625:web:67ec5b2c7dba66e8995af0',
    messagingSenderId: '21701660625',
    projectId: 'namma-kanyakumari',
    authDomain: 'namma-kanyakumari.firebaseapp.com',
    storageBucket: 'namma-kanyakumari.firebasestorage.app',
  );
}
