class AppStrings {
  static const Map<String, Map<String, String>> localizedValues = {
    'en': {
      'appName': 'Namma Kanyakumari',
      'appTagline': 'Citizen Grievance & District Services Portal',
      'welcomeBack': 'Welcome Back, Citizen',
      'login': 'Sign In',
      'register': 'Register as Citizen',
      'fullName': 'Full Name',
      'email': 'Email Address',
      'mobile': 'Mobile Number',
      'password': 'Password',
      'confirmPassword': 'Confirm Password',
      'forgotPassword': 'Forgot Password?',
      'home': 'Home',
      'complaints': 'Grievances',
      'emergency': 'Emergency',
      'services': 'Offices',
      'profile': 'Profile',
      'reportComplaint': 'Report Civic Issue',
      'fileNewIssue': 'File New Issue',
      'trackIssues': 'Track Grievances',
      'emergencyHotlines': 'District 24/7 Helplines',
      'collectorate': 'Kanyakumari Collectorate',
      'statusPending': 'Pending Verification',
      'statusInProgress': 'Action in Progress',
      'statusResolved': 'Resolved',
      'statusRejected': 'Rejected',
      'statusClosed': 'Closed',
      'quickSOS': 'One-Touch Rapid Emergency SOS',
      'language': 'Language',
      'darkMode': 'Dark Appearance',
      'logout': 'Log Out',
    },
    'ta': {
      'appName': 'நம்ம கன்னியாகுமரி',
      'appTagline': 'மக்கள் குறைதீர்க்கும் மாவட்ட நிர்வாக இணைய தளம்',
      'welcomeBack': 'நல்வரவு, பொதுமக்களே',
      'login': 'உள்நுழைக',
      'register': 'குடிமகன் பதிவு',
      'fullName': 'முழு பெயர்',
      'email': 'மின்னஞ்சல் முகவரி',
      'mobile': 'அலைபேசி எண்',
      'password': 'கடவுச்சொல்',
      'confirmPassword': 'கடவுச்சொல் உறுதி',
      'forgotPassword': 'கடவுச்சொல் மறந்துவிட்டதா?',
      'home': 'முகப்பு',
      'complaints': 'புகார்கள்',
      'emergency': 'அவசர உதவி',
      'services': 'அலுவலகங்கள்',
      'profile': 'சுயவிவரம்',
      'reportComplaint': 'குறை பதிவு செய்க',
      'fileNewIssue': 'புதிய புகார் செய்க',
      'trackIssues': 'புகார் நிலவரம்',
      'emergencyHotlines': 'மாவட்ட 24/7 அவசர எண்கள்',
      'collectorate': 'கன்னியாகுமரி மாவட்ட ஆட்சியர் அலுவலகம்',
      'statusPending': 'சரிபார்ப்பில் உள்ளது',
      'statusInProgress': 'நடவடிக்கையில் உள்ளது',
      'statusResolved': 'தீர்க்கப்பட்டது',
      'statusRejected': 'நிராகரிக்கப்பட்டது',
      'statusClosed': 'முடிவுற்றது',
      'quickSOS': 'உடனடி அவசர உதவி அழைப்பு',
      'language': 'மொழி',
      'darkMode': 'இரவு முறை',
      'logout': 'வெளியேறுக',
    }
  };

  static String get(String key, {String lang = 'en'}) {
    return localizedValues[lang]?[key] ?? localizedValues['en']?[key] ?? key;
  }
}
